export type { CaptionProps } from './Caption'
export { Caption } from './Caption'
export type { CodeProps } from './Code'
export { Code } from './Code'
export type { LeadProps } from './Lead'
export { Lead } from './Lead'
export type { SmallProps } from './Small'
export { Small } from './Small'
export type { SpanProps } from './Span'
export { Span } from './Span'
export type { SubtitleProps } from './Subtitle'
export { Subtitle } from './Subtitle'
export type { TextProps } from './Text'
export { Text } from './Text'
export type { TitleProps } from './Title'
export { Title } from './Title'
