export { AboutSection } from './AboutSection'
export { ContactSection } from './ContactSection'
export { EducationSection } from './EducationSection'
export { HeroSection } from './HeroSection'
export { ProjectsSection } from './ProjectsSection'
export { SkillsSection } from './SkillsSection'
